# This line can be removed as soon as latest stable Python is available in the default dist.
dist: xenial
language: python
python:
  - "3.5"
install:
  - pip install pycodestyle
  - pip install pylint==1.8.2
  - pip install mypy==0.670
script: make check
